seed: 20010920
device: !!python/object/apply:torch.device
- cuda
dataset: NYC
nary: 1
user_embed_dim: 128
POI_embed_dim: 128
time_embed_dim: 32
cat_embed_dim: 32
lon_parts: 32
lat_parts: 32
coo_embed_dim: 32
embed_dropout: 0.2
model_dropout: 0.4
h_size: 512
batch_size: 1024
accumulation_steps: 32
epochs: 120
lr: 0.001
lr_step_size: 6
lr_gamma: 0.9
weight_decay: 0.0001
plot_tree: false
workers: 0
port: 19923
save_path: ./checkpoints/
load_path: ''
