seed: 920
device: !!python/object/apply:torch.device
- cuda
dataset: NYC
data_train: dataset/NYC/NYC_train.csv
data_val: dataset/NYC/NYC_val.csv
data_test: dataset/NYC/NYC_test.csv
time_units: 48
time_feature: norm_in_day_time
user_embed_dim: 128
poi_embed_dim: 128
time_embed_dim: 32
cat_embed_dim: 32
gcn_dropout: 0.3
gcn_hidden_dim:
- 32
- 64
transformer_hidden_dim: 1024
transformer_layers: 2
transformer_heads: 2
transformer_dropout: 0.3
time_loss_weight: 10
node_attn_hidden_dim: 128
cell_type: nary
x_size: 256
h_size: 128
nary: 3
batch_size: 10
epochs: 200
lr: 0.001
lr_scheduler_factor: 0.1
weight_decay: 0.0005
save_weights: true
save_embeds: false
need_plot: false
workers: 0
exist_ok: false
no_cuda: false
mode: client
port: 19923
save_path: ./checkpoints/
