seed: 20010920
device: !!python/object/apply:torch.device
- cuda
dataset: NYC
cell_type: N-ary
nary: 3
user_embed_dim: 128
POI_embed_dim: 128
time_embed_dim: 32
cat_embed_dim: 32
lon_parts: 32
lat_parts: 32
coo_embed_dim: 32
transformer_head_num: 2
transformer_hid_dim: 1024
transformer_layer_num: 2
transformer_dropout: 0.3
h_size: 256
batch_size: 1024
epochs: 200
lr: 0.001
lr_scheduler_factor: 0.1
weight_decay: 0.0005
need_plot_tree: false
workers: 0
port: 19923
save_path: ./checkpoints/
load_path: ''
