seed: 920
device: !!python/object/apply:torch.device
- cuda
dataset: NYC
time_units: 48
time_feature: norm_in_day_time
user_embed_dim: 128
POI_embed_dim: 128
time_embed_dim: 32
cat_embed_dim: 32
time_loss_weight: 10
cell_type: nary
h_size: 128
nary: 3
batch_size: 32
epochs: 200
lr: 0.001
lr_scheduler_factor: 0.1
weight_decay: 0.0005
save_weights: true
save_embeds: false
need_plot_tree: false
workers: 0
port: 19923
save_path: ./checkpoints/
load_path: ''
